name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run generate

        - name: Make envfile
          uses: SpicyPizza/create-envfile@v1
          with:
            envkey_BASE_ROUTE: "http://seriescontrolapi-prod.sa-east-1.elasticbeanstalk.com/api/"
            directory: ./dist

        - name: copy env file
          uses: canastro/copy-file-action@master
          with:
            source: ".env"
            target: "dist/.env"

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: dist
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ${{ secrets.S3_BUCKET_REGION }}
            delete-removed: true
            no-cache: true
            private: true
